Fix get all NFTs bug on multiwrap
thirdweb-dev/typescript-sdk pull request #447
Opened 2022-06-02 20:51 UTC by adam-maj

2022-06-02 22:17 UTC, jnsdls commented
pretty significant change in behavior (just skip past failed tokens?)

also means we cannot rely on pagination anymore

2022-06-02 23:30 UTC, joaquim-verges commented on src/core/classes/erc-721-supply.ts
> +        const nft = await this.erc721.get(i);
this makes it all sequential which is super slow...

what's the problem you're trying solve here? just not throw on not found ?

2022-06-03 00:10 UTC, joaquim-verges requested changes
requires a change in the contract - the burn behavior is different than the other NFT contracts (should preserve URI and just set owner to address zero)

2022-06-03 18:48 UTC, joaquim-verges commented
closing this - just need to deploy the changes in the contract

2022-06-03 18:48 UTC, closed without merging